name: Ruby CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # 必要に応じてバージョンを変更

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec  # 必要に応じてテストコマンドを変更

      - name: Upload
        uses: actions/upload-artifact@v2 # 利用するアクションを指定
        if: failure() # 失敗したときだけ実行
        with:
         name: my-uploads
         path: tmp/screenshots/ # uploadするパス（Rails rootからの相対パス）

