name: Ruby on Rails & PostgreSQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: bundle install

    - name: Set up PostgreSQL
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo service postgresql start
        sudo -u postgres createuser --superuser "$USER"

    - name: Install and Compile Javascript with webpacker
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        yarn install --check-files
        bundle exec rails webpacker:install
        bundle exec rails webpacker:compile

    - name: Set up Database
      run: bundle exec rails db:migrate:reset
      env:
        RAILS_ENV: test

    - name: Run tests
      run: bundle exec rspec
      
    - name: Upload
      uses: actions/upload-artifact@v2 # 利用するアクションを指定
      if: failure() # 失敗したときだけ実行
      with:
        name: my-uploads
         path: tmp/screenshots/ # uploadするパス（Rails rootからの相対パス）
